USE [Learn1]
GO

/****** Object:  Table [dbo].[clientDetails]    Script Date: 12/18/2024 4:06:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[clientDetails](
	[client_key] [int] NOT NULL,
	[clientDetail_key] [int] NOT NULL,
	[adapfunc] [char](40) NOT NULL,
	[adaptdev] [text] NOT NULL,
	[admitted] [datetime] NOT NULL,
	[agept] [int] NOT NULL,
	[allergies] [text] NOT NULL,
	[appdate] [datetime] NOT NULL,
	[armhand] [char](40) NOT NULL,
	[assetmon] [char](20) NOT NULL,
	[assetyear] [int] NOT NULL,
	[assisdev] [text] NOT NULL,
	[bathing] [char](39) NOT NULL,
	[behavadapt] [text] NOT NULL,
	[behavexist] [bit] NOT NULL,
	[behavobjno] [char](6) NOT NULL,
	[behavtitle] [char](60) NOT NULL,
	[bfreefactr] [text] NOT NULL,
	[bgenhypoth] [text] NOT NULL,
	[bhvintrval] [char](6) NOT NULL,
	[bill_code] [char](4) NOT NULL,
	[bill_id] [char](8) NOT NULL,
	[birthday] [datetime] NOT NULL,
	[bloodtype] [char](11) NOT NULL,
	[bprecursor] [text] NOT NULL,
	[care_24hr] [bit] NOT NULL,
	[caseman] [char](50) NOT NULL,
	[classasuit] [char](35) NOT NULL,
	[commlvle] [char](40) NOT NULL,
	[commlvlr] [char](40) NOT NULL,
	[commmode] [char](40) NOT NULL,
	[commmodr] [char](40) NOT NULL,
	[complexton] [char](15) NOT NULL,
	[costtools] [float] NOT NULL,
	[costtrans] [float] NOT NULL,
	[countleg] [char](30) NULL,
	[county] [char](20) NOT NULL,
	[dayplace] [char](35) NOT NULL,
	[dayprogram] [char](15) NOT NULL,
	[dd] [bit] NOT NULL,
	[deldate] [datetime] NOT NULL,
	[detcode] [char](40) NOT NULL,
	[detdate] [datetime] NOT NULL,
	[diag] [text] NOT NULL,
	[diet] [text] NOT NULL,
	[discsum] [text] NOT NULL,
	[destrfreq] [char](40) NOT NULL,
	[destrsev] [char](40) NOT NULL,
	[disrfreq] [char](40) NOT NULL,
	[disrsev] [char](40) NOT NULL,
	[dol_adjuca] [datetime] NOT NULL,
	[dressing] [char](40) NOT NULL,
	[dsm4axis1] [text] NOT NULL,
	[dsm4axis2] [text] NOT NULL,
	[dsm4axis3] [text] NOT NULL,
	[dsm4axis4] [text] NOT NULL,
	[dsm4sofa] [int] NOT NULL,
	[dsmdiag] [text] NOT NULL,
	[eating] [char](40) NOT NULL,
	[educalvl] [char](40) NOT NULL,
	[employer] [char](30) NOT NULL,
	[empnohrs] [float] NOT NULL,
	[emptype] [char](20) NOT NULL,
	[ethnic] [char](40) NOT NULL,
	[excaseman] [char](35) NOT NULL,
	[eyecolor] [char](10) NOT NULL,
	[funpresnt] [text] NOT NULL,
	[funvision] [text] NOT NULL,
	[grooming] [char](40) NOT NULL,
	[group1] [char](20) NOT NULL,
	[group2] [char](20) NOT NULL,
	[haircolor] [char](15) NOT NULL,
	[health] [char](40) NOT NULL,
	[hearing] [char](86) NULL,
	[height] [char](5) NOT NULL,
	[hiredate] [datetime] NOT NULL,
	[homepresnt] [text] NOT NULL,
	[homevision] [text] NOT NULL,
	[homewaiver] [char](40) NOT NULL,
	[hphone] [char](14) NULL,
	[hrlyrate] [float] NOT NULL,
	[idmarks] [text] NOT NULL,
	[incnote] [text] NOT NULL,
	[insval] [float] NOT NULL,
	[intakestat] [char](40) NOT NULL,
	[ippdate] [datetime] NOT NULL,
	[is_current] [bit] NOT NULL,
	[langspok] [char](15) NOT NULL,
	[langus] [char](15) NOT NULL,
	[lastpdp] [datetime] NOT NULL,
	[lastplace] [char](35) NOT NULL,
	[legalcomp] [bit] NOT NULL,
	[lernpresnt] [text] NOT NULL,
	[lernvision] [text] NOT NULL,
	[location] [char](25) NULL,
	[maidnm] [char](20) NOT NULL,
	[marital] [char](40) NOT NULL,
	[meal] [char](40) NOT NULL,
	[medadapt] [text] NOT NULL,
	[medalert] [text] NOT NULL,
	[medicaid] [char](20) NOT NULL,
	[medicare] [char](20) NOT NULL,
	[mentfunc] [char](40) NOT NULL,
	[mobassist] [char](40) NOT NULL,
	[mobility] [char](40) NOT NULL,
	[mr] [bit] NOT NULL,
	[namerele] [bit] NOT NULL,
	[nextpdp] [datetime] NOT NULL,
	[notepad] [text] NOT NULL,
	[obj_met] [bit] NOT NULL,
	[offfreq] [char](40) NOT NULL,
	[offsev] [char](40) NOT NULL,
	[olades1] [char](20) NOT NULL,
	[olades2] [char](20) NOT NULL,
	[olades3] [char](20) NOT NULL,
	[olades4] [char](20) NOT NULL,
	[olades5] [char](20) NOT NULL,
	[olaval1] [float] NOT NULL,
	[olaval2] [float] NOT NULL,
	[olaval3] [float] NOT NULL,
	[olaval4] [float] NOT NULL,
	[olaval5] [float] NOT NULL,
	[oth2presnt] [text] NOT NULL,
	[oth2vision] [text] NOT NULL,
	[oth3presnt] [text] NOT NULL,
	[oth3vision] [text] NOT NULL,
	[othrace] [text] NOT NULL,
	[othrfreq] [char](40) NOT NULL,
	[othrpresnt] [text] NOT NULL,
	[othrsev] [char](40) NOT NULL,
	[othrvision] [text] NOT NULL,
	[palspresnt] [text] NOT NULL,
	[palsvision] [text] NOT NULL,
	[payamt] [float] NOT NULL,
	[paymonth] [char](20) NOT NULL,
	[pd] [bit] NOT NULL,
	[photoclr] [bit] NOT NULL,
	[physician] [char](60) NOT NULL,
	[picafreq] [char](40) NOT NULL,
	[picasev] [char](40) NOT NULL,
	[picfilename] [char](254) NULL,
	[picture] [image] NOT NULL,
	[pictureext] [char](4) NOT NULL,
	[plotval] [float] NOT NULL,
	[propval] [float] NOT NULL,
	[provision] [char](40) NOT NULL,
	[recstsupp] [float] NOT NULL,
	[relig_note] [text] NOT NULL,
	[religion] [char](35) NOT NULL,
	[rep_payee] [char](40) NOT NULL,
	[reppayee] [char](20) NOT NULL,
	[reptfreq] [char](40) NOT NULL,
	[reptsev] [char](40) NOT NULL,
	[resp_key] [int] NOT NULL,
	[resplace] [char](35) NOT NULL,
	[resprior] [char](35) NOT NULL,
	[revduedate] [datetime] NOT NULL,
	[revfirst] [char](16) NOT NULL,
	[revlast] [char](16) NOT NULL,
	[seizure] [char](40) NOT NULL,
	[selffreq] [char](40) NOT NULL,
	[selfsev] [char](40) NOT NULL,
	[sex] [char](20) NOT NULL,
	[site] [char](8) NOT NULL,
	[social] [char](40) NOT NULL,
	[ssn] [char](20) NOT NULL,
	[svcdate] [datetime] NOT NULL,
	[termdate] [datetime] NOT NULL,
	[toilet] [char](40) NOT NULL,
	[totalasset] [float] NOT NULL,
	[transfer] [char](40) NOT NULL,
	[treason] [text] NOT NULL,
	[triggrdate] [datetime] NOT NULL,
	[uimaint] [float] NOT NULL,
	[uimaothr] [float] NOT NULL,
	[uimapen] [float] NOT NULL,
	[uimarb] [float] NOT NULL,
	[uimasocsec] [float] NOT NULL,
	[uimassi] [float] NOT NULL,
	[uimatrust] [float] NOT NULL,
	[uimava] [float] NOT NULL,
	[uncoopfreq] [char](40) NOT NULL,
	[uncoopsev] [char](40) NOT NULL,
	[vehicval] [float] NOT NULL,
	[vision] [char](86) NULL,
	[visitor_rs] [text] NOT NULL,
	[vocaskills] [char](40) NOT NULL,
	[volunteer] [char](25) NOT NULL,
	[wanderfreq] [char](40) NOT NULL,
	[wandersev] [char](40) NOT NULL,
	[weight] [int] NOT NULL,
	[wibfreq] [char](40) NOT NULL,
	[wibsev] [char](40) NOT NULL,
	[workpresnt] [text] NOT NULL,
	[workvision] [text] NOT NULL,
	[wphone] [char](14) NULL,
	[wphonext] [char](20) NOT NULL,
	[ytdleave] [int] NOT NULL,
	[timestamp_column] [timestamp] NOT NULL,
	[disch_date] [datetime] NULL,
	[disch_time] [char](8) NULL,
	[disch_reason] [char](30) NULL,
	[bhvrsp_key] [int] NOT NULL,
	[is_uscitz] [bit] NOT NULL,
	[a_num] [char](10) NOT NULL,
	[a_numexpdt] [datetime] NOT NULL,
	[livunit_key] [int] NOT NULL,
	[mmaidname] [char](20) NOT NULL,
	[sname] [char](8) NOT NULL,
	[birthplace] [char](25) NOT NULL,
	[statefacid] [char](10) NOT NULL,
	[dfscaseid] [char](10) NOT NULL,
	[publicaidid] [char](10) NOT NULL,
	[claid] [char](30) NOT NULL,
	[gdnstat] [char](1) NOT NULL,
	[hispanicorigincode] [int] NOT NULL,
	[interpsvccode] [int] NOT NULL,
	[milstatcode] [int] NOT NULL,
	[courttreatmentcode] [int] NOT NULL,
	[ssi_ssdi_eligcode] [int] NOT NULL,
	[dfi_cfi_enroll] [char](1) NOT NULL,
	[tca_code] [int] NOT NULL,
	[cntyorigincode] [int] NOT NULL,
	[tca_origincode] [int] NOT NULL,
	[zipcode_origin] [char](10) NOT NULL,
	[regdate] [datetime] NOT NULL,
	[regrescode] [int] NOT NULL,
	[regcount] [int] NOT NULL,
	[closdate] [datetime] NOT NULL,
	[closrescode] [int] NOT NULL,
	[closcount] [int] NOT NULL,
	[closdispcode] [int] NOT NULL,
	[citizenshipcode] [int] NOT NULL,
	[ROCS_DnLoad] [bit] NOT NULL,
	[ROCSDD_DnLoad] [bit] NOT NULL,
	[ROCS_UpLoad] [bit] NOT NULL,
	[hospitalpref] [char](50) NOT NULL,
	[srcsuppins] [char](80) NOT NULL,
	[othragencies] [char](80) NOT NULL,
 CONSTRAINT [PK_clientDetails] PRIMARY KEY CLUSTERED 
(
	[clientDetail_key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


