using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace DataModels.Models.Entities
{
    public class AgencyInfo
    {
        //[Key]
        //public int Id { get; set; }
       
        public string adultguard { get; set; } = string.Empty;
        public bool advansecur { get; set; } = false;
        public string agencycode { get; set; } = string.Empty;
        public string agencyname { get; set; } = string.Empty;
        public bool allmonth { get; set; } = false;
        public string altcliname { get; set; } = string.Empty;
        public bool baseinnote { get; set; } = false;
        public string bgpic { get; set; } = string.Empty;
        public bool billobject { get; set; } = false;
        public bool bl_allow { get; set; } = false;
        public string bl_map { get; set; } = string.Empty;
        public bool blocksign { get; set; } = false;
        public bool canblast { get; set; } = false;
        public string catgry_key { get; set; } = string.Empty;
        public bool chkoradv { get; set; } = false;
        public string corp_path { get; set; } = string.Empty;
        public int cr_overdue { get; set; } = 0;
        public bool dailygraf { get; set; } = false;
        public string dateformat { get; set; } = string.Empty;
        public string demouser1 { get; set; } = string.Empty;
        public string demouser2 { get; set; } = string.Empty;
        public string demouser3 { get; set; } = string.Empty;
        public bool dosesshist { get; set; } = false;
        public string domain_key { get; set; } = string.Empty;
        public bool enablegwiz { get; set; } = false;
        public int epochyear { get; set; } = 0;
        public string exename { get; set; } = string.Empty;
        public bool fourdigtyr { get; set; } = false;
        public string from_psite { get; set; } = string.Empty;
        public string goalib_key { get; set; } = string.Empty;
        public string goalsnm { get; set; } = string.Empty;
        public string group_key { get; set; } = string.Empty;
        public string guardiannm { get; set; } = string.Empty;
        public bool hds_compat { get; set; } = false;
        public bool importer { get; set; } = false;
        public Int16 inactivity { get; set; } = 0;
        public bool is_both { get; set; } = false;
        public bool is_corp { get; set; } = false;
        public string iwill { get; set; } = string.Empty;
        public int keepactv { get; set; } = 0;
        public int keepai { get; set; } = 0;
        public bool keepassess { get; set; } = false;
        public int keepbillin { get; set; } = 0;
        public int keepelog { get; set; } = 0;
        public int keephist { get; set; } = 0;
        public int keepnotes { get; set; } = 0;
        public int keeprevs { get; set; } = 0;
        public int keepserv { get; set; } = 0;
        public int keepsess { get; set; } = 0;
        public int keepstac { get; set; } = 0;
        public bool keep_open { get; set; } = false;
        public bool lastdaymon { get; set; } = false;
        public DateTime lasticheck { get; set; } = DateTime.Now;
        public DateTime lastpurge { get; set; } = DateTime.Now;
        public int lastsnapdr { get; set; } = 0;
        public DateTime lastsnapdt { get; set; } = DateTime.Now;
        public string librar_key { get; set; } = string.Empty;
        public bool longdates { get; set; } = false;
        public string makefolder { get; set; } = string.Empty;
        public Int16 minpasslen { get; set; } = 0;
        public int monsnoprog { get; set; } = 0;
        public bool multikeyok { get; set; } = false;
        public bool nobehavior { get; set; } = false;
        public bool nobkg { get; set; } = false;
        public bool noclient { get; set; } = false;
        public bool nonaminuse { get; set; } = false;
        public bool norollfwd { get; set; } = false;
        public bool notetext { get; set; } = false;
        public string objname { get; set; } = string.Empty;
        public bool oneapage { get; set; } = false;
        public bool pagefactor { get; set; } = false;
        public string permision2 { get; set; } = string.Empty;
        public string permission { get; set; } = string.Empty;
        public string plan_key { get; set; } = string.Empty;
        public int pn_overdue { get; set; } = 0;
        public string progplannm { get; set; } = string.Empty;
        public string progrm_key { get; set; } = string.Empty;
        public string prompt_e1 { get; set; } = string.Empty;
        public string prompt_e2 { get; set; } = string.Empty;
        public string prompt_e3 { get; set; } = string.Empty;
        public string providernm { get; set; } = string.Empty;
        public bool p_banner { get; set; } = false;
        public string p_name1 { get; set; } = string.Empty;
        public string p_name2 { get; set; } = string.Empty;
        public string p_name3 { get; set; } = string.Empty;
        public string p_name4 { get; set; } = string.Empty;
        public string p_name5 { get; set; } = string.Empty;
        public string p_name6 { get; set; } = string.Empty;
        public string recordbehv { get; set; } = string.Empty;
        public double remoteno { get; set; } = 0;
        public string reviewernm { get; set; } = string.Empty;
        public string reviewtyps { get; set; } = string.Empty;
        public string revprefixs { get; set; } = string.Empty;
        public bool scalable1 { get; set; } = false;
        public string scales_key { get; set; } = string.Empty;
        public bool send_pdocs { get; set; } = false;
        public bool send_pics { get; set; } = false;
        public bool send_rdocs { get; set; } = false;
        public string servoname { get; set; } = string.Empty;
        public string site { get; set; } = string.Empty;
        public string snapfreq { get; set; } = string.Empty;
        public bool snapmnthly { get; set; } = false;
        public string snaprotate { get; set; } = string.Empty;
        public bool snapyearly { get; set; } = false;
        public string staffuser1 { get; set; } = string.Empty;
        public string staffuser2 { get; set; } = string.Empty;
        public string staffuser3 { get; set; } = string.Empty;
        public string staff_key { get; set; } = string.Empty;
        public bool stepdates { get; set; } = false;
        public bool stepercent { get; set; } = false;
        public string stepname { get; set; } = string.Empty;
        public bool stopicheck { get; set; } = false;
        public int strennum { get; set; } = 0;
        public bool targetgoal { get; set; } = false;
        public double timeout { get; set; } = 0;
        public string trainname { get; set; } = string.Empty;
        public bool ugly { get; set; } = false;
        public string version { get; set; } = string.Empty;
        public string visioname1 { get; set; } = string.Empty;
        public string visioname2 { get; set; } = string.Empty;
        public string visioname3 { get; set; } = string.Empty;
        public string visioname4 { get; set; } = string.Empty;
        public string visioname5 { get; set; } = string.Empty;
        public string visioname6 { get; set; } = string.Empty;
        public string visioname7 { get; set; } = string.Empty;
        public string visioname8 { get; set; } = string.Empty;
        public int weaknum { get; set; } = 0;
        public string wppath { get; set; } = string.Empty;
        public string xcasemannm { get; set; } = string.Empty;
        public string yourplan1 { get; set; } = string.Empty;
        public string yourplan2 { get; set; } = string.Empty;
        public string yourplan3 { get; set; } = string.Empty;
        public string yourplan4 { get; set; } = string.Empty;
        public string yourplan5 { get; set; } = string.Empty;
        public Byte[] timestamp_column { get; set; }
        [Key]
        public int sysinfo_key { get; set; } = 0;
        public bool obj_author { get; set; } = false;
        public bool prefer_wp { get; set; } = false;
        public bool nodupobj { get; set; } = false;
        public string subagencyname { get; set; } = string.Empty;
        public string customcode { get; set; } = string.Empty;
        public string clikinprom { get; set; } = string.Empty;
        public bool nodupobjno { get; set; } = false;
        public bool requsernam { get; set; } = false;
        public bool USECRITERI { get; set; } = false;
        public byte[] helpfile { get; set; }
        public byte[] xsltemplat { get; set; }
        public string careplantitle { get; set; } = string.Empty;
        public DateTime permissage { get; set; } = DateTime.Now;
        public string patchlog { get; set; } = string.Empty;
        public string criteriaprint { get; set; } = string.Empty;
        public string agencyadr1 { get; set; } = string.Empty;
        public string agencyadr2 { get; set; } = string.Empty;
        public string agencycity { get; set; } = string.Empty;
        public string agencystate { get; set; } = string.Empty;
        public string agencyzip { get; set; } = string.Empty;
        public string agencybphone { get; set; } = string.Empty;
        public bool usecensus { get; set; } = false;
        public string provmedicaidid { get; set; } = string.Empty;
        public string provmedicareid { get; set; } = string.Empty;
        public string provvendorid { get; set; } = string.Empty;
        public string provEIN { get; set; } = string.Empty;
        public string provNPI { get; set; } = string.Empty;
        public bool ai_listbox { get; set; } = false;
        public string procodefil { get; set; } = string.Empty;
        public bool mayenter0 { get; set; } = false;
        public string append_to_connection_string { get; set; } = string.Empty;
        public string lastbackupdone { get; set; } = string.Empty;
    }
}
